version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pa55w0rd!
      - MSSQL_SA_PASSWORD=Pa55w0rd!
      - MSSQL_PID=Express
    ports:
      - 1433:1433
  api:
    build: .
    environment:
      - DBServer=db
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      - db
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
    working_dir: /app
    entrypoint: [
               './wait-for-it.sh',
               'db:1433',
               '-t',
               '90',
               '--',
               'dotnet',
               'Commander.dll',               
    ]